[package]
name = "aegis-tc"
version = "0.1.0"
edition = "2021"

[dependencies]
aya-ebpf = "0.1.1"
aegis-common = { path = "../aegis-common", default-features = false }

[[bin]]
name = "aegis-tc"
path = "src/main.rs"
