[package]
name = "aegis-common"
version = "0.1.0"
edition = "2021"

[features]
user = ["dep:serde"]

[dependencies]
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
